name: Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: CD part
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-name: ['em-backend']
        # s3-bucket: ['swd-code-deploy']
        # s3-filename: ['swd-code-deploy-${{ github.sha }}']
        deploy-group: ['dev']
    steps:
      - uses: actions/checkout@v2

      # Install AWS CLI 2
      - name: Install AWS CLI 2
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64
      # Configure AWS credentials
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # Deploy push to S3
      # - name: AWS Deploy push
      #   run: |
      #     aws deploy push \
      #     --application-name ${{ matrix.app-name }} \
      #     --description "Revision of the ${{ matrix.appname }}-${{ github.sha }}" \
      #     --ignore-hidden-files \
      #     --s3-location s3://${{ matrix.s3-bucket }}/${{ matrix.s3-filename }}.zip \
      #     --source .
      # Creating deployment via CodeDeploy
      # - name: Creating AWS Deployment
      #   run: |
      #     aws deploy create-deployment \
      #     --application-name ${{ matrix.app-name }} \
      #     --deployment-config-name CodeDeployDefault.AllAtOnce \
      #     --deployment-group-name ${{ matrix.deploy-group }} \
      #     --file-exists-behavior OVERWRITE \
      #     --s3-location bucket=${{ matrix.s3-bucket }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \